### ISSUE TITLE
Support JDBC XA transaction

### ISSUE THREAD

**Issue by cherrylzhao** [sharding-sphere/sharding-sphere#1363]
* [x] split transaction manager and datasource
   * [x] investigate AtomikosDatasourceBean
   * [x] investigate BasicManagedDataSource
   * [x] make Atomikos and DBCP2 XA datasource configurable.
 * [x] inject xa datasource into shardingDatasource
   * [x] add SPI for XABackendDatasource
   * [x] make datasourceMap and xaDatasourceMap compatible.
   * [x] normal datasource convert to XA transactional datasource.
* [x] add switch controls within transaction type changes
   * [x] switch for ShardingDatasource.
   * [x] switch for MasterSlaveDatasource.
   * [x] switch for OrchestrationDataSource.
 * [x] XA recovery
   * [x] AtomikosDataSourceBean recovery
   * [x] BasicManagedDataSource recovery
 * [x] refactor sharding-transaction  module.
   * [x] add sharding-transaction-api.
   * [x] add sharding-transaction-base.
   * [x] add sharding-transaction-xa.
 * [x] using SPI instead of guava event bus
 * [x] XA database support
   * [x] consider about use SPI to load database driver. #1441 
   * [x] XA for Mysql.
   * [x] XA for H2.
   * [x] XA for PostgreSql.
   * [x] XA for SqlServer.
   * [x] XA for Oracle.
 * [x] none XA datasource adapter
   * [x] Consider about use DataSourceConfiguration and reflection to generate data source
      * [x] create DataSourcePramete by DataSourceConfiguration
      * [x] reflection to generate data source [not support]
   * [x] adapte for Hikari
   * [x] adapte for DBCP2
   * [x] adapte for Druid
 * [x] add XA JDBC example
   * [x] add XA transaction type configuration

**Comment by terrymanu** [comment]
TODO: 
1. Consider about use `DataSourceConfiguration` and reflection to generate data source.
2. Use SPI instead of Guava event bus to process transaction for performance issue.
3. Use SPI to load database driver.

Questions:
1. Why choose TOMCAT_DBCP2 database connection pool by default XA transaction manger? Why not Atomikos?
2. What is `BackendDataSourceFactory`, if it only related with XA, maybe we should rename it.
3. `XABackendDataSourceFactory` is the main implantation of `BackendDataSourceFactory`,  maybe we can remove `BackendDataSourceFactory`. If you want create some test fixture on them, just use mock.
4. `JDBCBackendDataSourceFactory` is not a sub class of `BackendDataSourceFactory`, here maybe need a little refactor.
5. Why `XABackendDataSourceConverter` need to implements `BackendDataSourceFactory`?
6. Maybe we should initial XA data source on startup, it can avoid sync. Maybe we can judge via SPI to know XA transaction manager is existed.
7. `XABackendDataSourceConverter` has already in your source code, why need SPI to inject it?

To be discuss:
1. Create XA data source will need 2 times for database connection, because we need to keep 2 types of data source map, any resolution to avoid it? If we use XA data source, but don't open XA transaction, is it possible work fine just like regular data source?

**Comment by cherrylzhao** [comment]
> TODO:
> 
> 1. Consider about use `DataSourceConfiguration` and reflection to generate data source.
> 2. Use SPI instead of Guava event bus to process transaction for performance issue.
> 3. Use SPI to load database driver.
> 

OK

> Questions:
> 
> 1. Why choose TOMCAT_DBCP2 database connection pool by default XA transaction manger? Why not Atomikos?

**Default is AtomikosDatasourceBean，TOMCAT_DBCP2 was recommended by redHat team, they have integrated succeed using it.**

> 2. What is `BackendDataSourceFactory`, if it only related with XA, maybe we should rename it.

**this is factory interface for convert normal datasource to XA transactional datasource.**

> 3. `XABackendDataSourceFactory` is the main implantation of `BackendDataSourceFactory`,  maybe we can remove `BackendDataSourceFactory`. If you want create some test fixture on them, just use mock.

**XABackendDataSourceFactory is only the serviceLoader for finding the implementation in swarding-transaction,** 

> 4. `JDBCBackendDataSourceFactory` is not a sub class of `BackendDataSourceFactory`, here maybe need a little refactor.

these two class has not relation, I have considered two refactor JDBCBackendDataSourceFactory,
but these two designed in different way in top level.

> 5. Why `XABackendDataSourceConverter` need to implements `BackendDataSourceFactory`?
> 7. `XABackendDataSourceConverter` has already in your source code, why need SPI to inject it?

I chose spi way to implement BackendDataSourceConvert, sharding-jdbc will only dependency spi interface, I'll change it later.

> 6. Maybe we should initial XA data source on startup, it can avoid sync. Maybe we can judge via SPI to know XA transaction manager is existed.

yes, I'll refactor it like that.

> To be discuss:
> 
> 1. Create XA data source will need 2 times for database connection, because we need to keep 2 types of data source map, any resolution to avoid it? If we use XA data source, but don't open XA transaction, is it possible work fine just like regular data source?

I have listed the task in `add switch controls within transaction type changes`, i'll resolve these issues later.
