### ISSUE TITLE
I have two databases, for example Db_a, db_b Sharding JDBC branch does not support db_a_master db_a_slave, db_b_master,db_b_slave？

### ISSUE THREAD

**Issue by ittimeline** [sharding-sphere/sharding-sphere#1383]
I have two databases, for example
Db_a, db_b
Sharding JDBC branch does not support db_a_master db_a_slave, db_b_master,db_b_slave？

**Comment by terrymanu** [comment]
Yes, it support. Duplicated with #1381

Before ask question, cloud you prepare to do something follow the question template?

Template:

## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
