### ISSUE TITLE
ERROR 1264 (22001): Data truncation: Out of range value for column 'order_id' at row 1

### ISSUE THREAD

**Issue by Super-Alan** [sharding-sphere/sharding-sphere#1453]
When I  try to use  Sharding-Proxy,I found the follow sql statement isn't working,but in native mysql it works; I don't know how to fix it!
`insert into tbl_order (actual_pay, created_date, customer_id, mobile, pay_date, sum, user_name, user_remain) values(1.0,'2018-11-01 11:00:01',1,'11',null,1,'alan',11)`

order_id is  auto increment key

**Comment by terrymanu** [comment]
Please provide more information like below:


## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by Super-Alan** [comment]
Project:Sharding-Proxy 3.0.0
Expected behavior: when inserting data ， Sharding-proxy can  create a unique id automatically 
Actual behavior:  sql error: ERROR 1264 (22001)
 
When I use jpa with Sharding-proxy ,find this problem,but  I also have tried to insert by mysql-client ,it's still not working

config-sharding code: [https://coding.net/u/Super-Alan/p/saga-transaction/git/blob/ms-tcc-zuul/config-sharding.yaml](url)

create database sql: [https://coding.net/u/Super-Alan/p/saga-transaction/git/blob/ms-tcc-zuul/order/src/main/resources/order-sharding.sql](url)

[https://coding.net/u/Super-Alan/p/saga-transaction/git/blob/ms-tcc-zuul/order/src/main/resources/order-sharding1.sql](url)

**Comment by terrymanu** [comment]
I cannot access the url  https://coding.net/u/Super-Alan/p/saga-transaction/git/blob/ms-tcc-zuul/config-sharding.yaml
Could you mind put your sql and yaml on github? or just paste them as text?

**Comment by terrymanu** [comment]
ok, we will investigate soon

**Comment by loxp** [comment]
> When I try to use Sharding-Proxy,I found the follow sql statement isn't working,but in native mysql it works; I don't know how to fix it!
> `insert into tbl_order (actual_pay, created_date, customer_id, mobile, pay_date, sum, user_name, user_remain) values(1.0,'2018-11-01 11:00:01',1,'11',null,1,'alan',11)`
> 
> order_id is auto increment key

since id generated by DefaultKeyGenerator is a java `long` type, please use `bigint` datatype for order_id column.
