### ISSUE TITLE
java.lang.IllegalStateException: no table route info

### ISSUE THREAD

**Issue by offSwitch** [sharding-sphere/sharding-sphere#1513]
## Question

stracktrace
at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at io.shardingsphere.core.routing.type.standard.StandardRoutingEngine.routeTables(StandardRoutingEngine.java:165)
	at io.shardingsphere.core.routing.type.standard.StandardRoutingEngine.route(StandardRoutingEngine.java:77)
	at io.shardingsphere.core.routing.type.standard.StandardRoutingEngine.routeByShardingConditions(StandardRoutingEngine.java:111)
	at io.shardingsphere.core.routing.type.standard.StandardRoutingEngine.route(StandardRoutingEngine.java:68)
	at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.route(ParsingSQLRouter.java:154)
	at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.route(ParsingSQLRouter.java:113)
	at io.shardingsphere.core.routing.StatementRoutingEngine.route(StatementRoutingEngine.java:57)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingStatement.sqlRoute(ShardingStatement.java:251)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingStatement.execute(ShardingStatement.java:162)

source:

  Map<String, DataSource> dataSourceMap = new HashMap<>();
	    BasicDataSource dataSource1 = new BasicDataSource();
	    dataSource1.setDriverClassName("com.mysql.jdbc.Driver");
	    dataSource1.setUsername("root");
	    dataSource1.setPassword("root");
	    dataSource1.setUrl("jdbc:mysql://192.168.135.130:3306/ds0");
	    dataSourceMap.put("ds0", dataSource1);

	    BasicDataSource dataSource2 = new BasicDataSource();
	    dataSource2.setDriverClassName("com.mysql.jdbc.Driver");
	    dataSource2.setUsername("root");
	    dataSource2.setPassword("root");
	    dataSource2.setUrl("jdbc:mysql://192.168.135.130:3306/ds1");
	    dataSourceMap.put("ds1", dataSource2);

	    TableRuleConfiguration orderTableRuleConfig = new TableRuleConfiguration();
	    orderTableRuleConfig.setLogicTable("t_order");
	    orderTableRuleConfig.setActualDataNodes("ds${0..1}.t_order${0..1}");
	    orderTableRuleConfig.setDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("user_id", "ds${user_id % 2}"));
	    orderTableRuleConfig.setDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("order_id", "t_order${order_id % 2}"));
	    ShardingRuleConfiguration shardingRuleConfiguration = new ShardingRuleConfiguration();
	    shardingRuleConfiguration.getTableRuleConfigs().add(orderTableRuleConfig);

	    DataSource dataSource = ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfiguration, new ConcurrentHashMap<>(), new Properties());
	    Connection connection = dataSource.getConnection();
	    Statement stat = connection.createStatement();
	    stat.execute("insert into t_order(order_id,user_id,create_time) values(0,0,current_date)");
	    connection.close();

**Comment by terrymanu** [comment]
Can you provide more information？ You can just fill the table below:


## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by offSwitch** [comment]
### Which version of Sharding-Sphere did you use?
3.0.0

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-jdbc

### Expected behavior
insert into ds0 t_order0  success

### Actual behavior
throw Exception, no table route info


### Reason analyze (If you can)


### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
Any reason to close this issue?
