### ISSUE TITLE
support varbinary

### ISSUE THREAD

**Issue by baisijian** [sharding-sphere/sharding-sphere#1579]
## Feature Request
sharding support key type is varbinary 
in sharding code
1. in OrderValue.java by issue need to transfer byte[] to string
2. in BasicExpressionParse.java parseExpression() need to support unhex sql sytax
**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by tuohai666** [comment]
To improve productivity please answer the questions below:

### Which version of Sharding-Sphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
@baisijian Hi, if no response anymore, we will close this issue after 2 days

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.
