### ISSUE TITLE
why so much memory consumption of groovy

### ISSUE THREAD

**Issue by zhushikun** [sharding-sphere/sharding-sphere#984]
![image](https://user-images.githubusercontent.com/4970679/42300491-6324c1ae-8043-11e8-8a1a-c3d04536091f.png)

related dependencies:
+--- io.shardingsphere:sharding-jdbc:3.0.0.M1
|    +--- io.shardingsphere:sharding-core:3.0.0.M1
|    |    +--- com.google.guava:guava:18.0 -> 20.0
|    |    +--- org.apache.commons:commons-lang3:3.6 -> 3.5
|    |    +--- org.codehaus.groovy:groovy:2.4.5 -> 2.4.12
|    |    +--- org.yaml:snakeyaml:1.16 -> 1.17
|    |    \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.25
|    +--- com.google.guava:guava:18.0 -> 20.0
|    +--- org.apache.commons:commons-lang3:3.6 -> 3.5
|    +--- org.codehaus.groovy:groovy:2.4.5 -> 2.4.12
|    +--- org.yaml:snakeyaml:1.16 -> 1.17
|    \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.25

**Comment by zhushikun** [comment]
note:  these created Objs always keep in memory, even full GC can't  free these objs

**Comment by jakara** [comment]
found this issue also in my project, the memory resource will run out and tomcat will freeze
gota have some memory leak here?
![memory leak](https://user-images.githubusercontent.com/1069864/42308903-b447bc78-8069-11e8-9fc9-c9abd05b3712.png)

**Comment by jakara** [comment]
did some research with groovy related codes, only 2 classes uses groovy: InlineExpressionParser and InlineShardingStrategy. As I do not use InlineShardingStrategy, so I guess the bug is caused by InlineExpressionParser .

at alst I found when getTableRule from ShardingRule, it will createTableRuleWithDefaultDataSource everytime  if no datasource configed for a logic table, and this will create groovyShell each time, so I made a PR to fix this, not sure any other defects related to this bug

https://github.com/sharding-sphere/sharding-sphere/pull/985/files

**Comment by terrymanu** [comment]
duplicate with #919
