### ISSUE TITLE
sharding-proxy hang-up when entering "use sharding-db" instruction 

### ISSUE THREAD

**Issue by cherrylzhao** [sharding-sphere/sharding-sphere#992]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
sharding-proxy 3.0.0.M2-SNAPSHOT

### Expected behavior
"use sharing_db" instructions can return successfully.

### Actual behavior
suspended in command-line

### Steps to reproduce the behavior
- mysql -h127.0.0.1 -P3307 -uroot -proot
- use sharding_db

**Comment by tristaZero** [comment]
When the DataSourceName configured  is different with the actual database name, the statement 'SHOW COLUMNS FROM tbl_name [FROM db_name] ' will get error. This is because the sharding SQLBuilder can not can the actual database name to replace the defualt database name.

So, this enhancement will analyze JDBC Url to get the actual database name to replace the  defualt database name.

**Comment by tristaZero** [comment]
fixed in Support authorization parsing for Sharding core #996.
